source ~/.zplug/zplug

zplug "b4b4r07/zplug"
zplug "supercrabtree/k"
zplug "chrissicool/zsh-256color"
zplug "plugins/z", from:oh-my-zsh
zplug "plugins/git", from:oh-my-zsh, if:"which git"
zplug "themes/bureau", from:oh-my-zsh
zplug "lib/clipboard", from:oh-my-zsh, if:"[[ $OSTYPE == *darwin* ]]"

if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

# Then, source plugins and add commands to $PATH
zplug load --verbose

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
eval "$(direnv hook zsh)"

[[ -a ~/.zshrc_local ]] && source ~/.zshrc_local
