source ~/.zplug/init.zsh

zplug "b4b4r07/zplug"

zplug "supercrabtree/k"
zplug "plugins/z", from:oh-my-zsh
# Colors
zplug "chrissicool/zsh-256color"
zplug "zsh-users/zsh-completions"
zplug "themes/af-magic", from:oh-my-zsh
zplug "lib/completion", from:oh-my-zsh
zplug "lib/history", from:oh-my-zsh
zplug "lib/directories", from:oh-my-zsh
zplug "lib/grep", from:oh-my-zsh
zplug "lib/spectrum", from:oh-my-zsh
zplug "lib/termsupport", from:oh-my-zsh
zplug "lib/theme-and-appearance", from:oh-my-zsh
zplug "lib/clipboard", from:oh-my-zsh, if:"[[ $OSTYPE == *darwin* ]]"
zplug "plugins/git", from:oh-my-zsh, if:"which git", defer:2
zplug "horosgrisa/autoenv"
zplug "jhipster/jhipster-oh-my-zsh-plugin"

if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

# Then, source plugins and add commands to $PATH
zplug load

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export EDITOR=vim

if type direnv > /dev/null 2>&1; then
  eval "$(direnv hook zsh)"
fi

function mkeo() {
    echo "OLDPATH_AE=\$PATH\nexport PATH=\$PATH" > $1/.env
    echo "export PATH=\$OLDPATH_AE" > $1/.out
}

[[ -a ~/.zshrc_local ]] && source ~/.zshrc_local

# tabtab source for jhipster package
# uninstall by removing these lines or running `tabtab uninstall jhipster`
[[ -f /usr/local/lib/node_modules/generator-jhipster/node_modules/tabtab/.completions/jhipster.zsh ]] && . /usr/local/lib/node_modules/generator-jhipster/node_modules/tabtab/.completions/jhipster.zsh

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"
