source ~/.zplug/init.zsh

zplug 'zplug/zplug', hook-build:'zplug --self-manage'

zplug "rupa/z", use:z.sh
zplug "supercrabtree/k"
# Colors
zplug "chrissicool/zsh-256color"
zplug "zsh-users/zsh-completions"
zplug "lib/functions", from:oh-my-zsh
zplug "themes/af-magic", from:oh-my-zsh
zplug "lib/completion", from:oh-my-zsh
zplug "lib/history", from:oh-my-zsh
zplug "lib/directories", from:oh-my-zsh
zplug "lib/grep", from:oh-my-zsh
zplug "lib/spectrum", from:oh-my-zsh
zplug "lib/termsupport", from:oh-my-zsh
zplug "lib/theme-and-appearance", from:oh-my-zsh
zplug "lib/clipboard", from:oh-my-zsh, if:"[[ $OSTYPE == *darwin* ]]"
zplug "plugins/git", from:oh-my-zsh, if:"which git", defer:2
zplug "horosgrisa/autoenv"
zplug "jhipster/jhipster-oh-my-zsh-plugin"

if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

# Then, source plugins and add commands to $PATH
zplug load

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export EDITOR=vim

if type direnv > /dev/null 2>&1; then
  eval "$(direnv hook zsh)"
fi

[[ -a ~/.zshrc_local ]] && source ~/.zshrc_local

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
export PATH="/usr/local/opt/bison/bin:$PATH"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export PATH="/usr/local/opt/openssl/bin:$PATH"

# Aliases

alias cats='highlight -O ansi --force'
